spring:
  rabbitmq:
    ssl:
      enabled: false

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0ms
  mvc:
    async:
      request-timeout: 10000ms

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments : true
  flyway:
    enabled: false
  liquibase:
    enabled: false

  quartz:
    jdbc:
      initialize-schema: always
#      schema: classpath:seeds/quartz.sql

logging:
  level:
    org.springframework: TRACE
    org.hibernate: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG
    com.mysql: DEBUG
