apiVersion: v1
kind: Service
metadata:
  name: dev-mysql
  labels:
    app: dev
spec:
  ports:
    - port: 3306
  selector:
    app: dev
    env: workstation
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dev-mysql
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
      env: workstation
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
        env: workstation
        tier: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
#          args:
#            - "--default-authentication-plugin=mysql_native_password"
          env:
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              value: "dev_local"
            - name: MYSQL_ROOT_PASSWORD
              value: "passw0rd"
            - name: MYSQL_USER
              value: "user01"
            - name: MYSQL_PASSWORD
              value: "passw0rd"
          ports:
            - name: mysql
              protocol: TCP
              containerPort: 3306
#          volumeMounts:
#            - name: mysql-persistent-storage
#              mountPath: /var/lib/mysql
#      volumes:
#        - name: mysql-persistent-storage
#          persistentVolumeClaim:
#            claimName: mysql-pv-claim
